config/routes.rb
Rails.application.routes.draw do
  resource :session
  resources :passwords, param: :token
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "dashboard#show"

  resources :commodities, only: %i[index show] do
    get "/purchase", on: :member, to: "commodity_transactions#new", defaults: { transaction_type: CommodityTransaction::TYPE_PURCHASE }, as: :purchase
    get "/sell", on: :member, to: "commodity_transactions#new", defaults: { transaction_type: CommodityTransaction::TYPE_SALE }, as: :sell

    resources :commodity_transactions, only: %i[create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/commodity.rb
class Commodity < ApplicationRecord
  has_many :commodity_ownerships, dependent: :destroy
  has_many :commodity_transactions, dependent: :destroy
  has_many :commodity_adjustments, dependent: :destroy

  def adjust_price(price_change)
    transaction do
      self.price += price_change
      commodity_adjustments.create!(price_change: price_change)

      if self.price <= 0
        Rails.logger.info "Price of #{name} has dropped to zero. Destroying all commodity_ownerships"
        commodity_ownerships.destroy_all

        self.price = 100
      elsif self.price >= 200
        Rails.logger.info "Price of #{name} is above 200. Splitting the stocks"
        commodity_ownerships.update_all("quantity = quantity * 2")

        self.price = 100
      end

      save!
    end
  end
end

app/models/commodity_adjustment.rb
class CommodityAdjustment < ApplicationRecord
  belongs_to :commodity

  validates :price_change, presence: true
  validates :commodity, presence: true
end

app/models/commodity_ownership.rb
class CommodityOwnership < ApplicationRecord
  belongs_to :commodity
  belongs_to :user

  validates :commodity_id, uniqueness: { scope: :user_id }
  validates :user_id, presence: true
  validates :commodity_id, presence: true
  validates :quantity, presence: true, numericality: { greater_than_eq: 0 }

  scope :with_total_value, -> {
    select("commodity_ownerships.*, (commodity_ownerships.quantity * commodities.price) as total_value").
      joins(:commodity)
  }
end

app/models/commodity_transaction.rb
class CommodityTransaction < ApplicationRecord
  TYPE_SALE='sale'.freeze
  TYPE_PURCHASE='purchase'.freeze
  TYPES=[TYPE_SALE, TYPE_PURCHASE].freeze

  belongs_to :commodity
  belongs_to :user

  validates :commodity_id, presence: true
  validates :user_id, presence: true
  validates :quantity, presence: true, numericality: { greater_than: 0 }
  validates :price, presence: true, numericality: { greater_than: 0 }
  validates :transaction_type, presence: true, inclusion: { in: TYPES }

  TYPES.each do |type|
    define_method("#{type}?") do
      transaction_type == type
    end
  end
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :session
  delegate :user, to: :session, allow_nil: true
end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :sessions, dependent: :destroy
  has_many :commodity_ownerships, dependent: :destroy
  has_many :commodity_transactions, dependent: :destroy

  validates :email, presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  normalizes :email, with: ->(e) { e.strip.downcase }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authentication
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/commodities_controller.rb
class CommoditiesController < ApplicationController
  # def index
  #   @commodities = Commodity.all
  # end

  def show
    @commodity = Commodity.find(params[:id])
    @commodity_owned = Current.user.commodity_ownerships.find_by(commodity_id: @commodity.id)&.quantity || 0
  end
end

app/controllers/commodity_transactions_controller.rb
class CommodityTransactionsController < ApplicationController
  def new
    @commodity = Commodity.find(params[:id])
    @commodity_transaction = Current.user.commodity_transactions.new(commodity: @commodity, transaction_type: params[:transaction_type])
  end

  def create
    @commodity = Commodity.find(params[:commodity_id])
    @commodity_transaction = Current.user.commodity_transactions.new(commodity_transaction_params.merge(commodity: @commodity))

    if CommodityTransactions::ValidateTransaction.call(commodity_transaction: @commodity_transaction)
      redirect_to root_path, notice: "Transaction successful"
    else
      render :new, alert: "Transaction failed"
    end
  end

  private

  def commodity_transaction_params
    params.require(:commodity_transaction).permit(:quantity, :transaction_type)
  end
end

app/controllers/concerns/authentication.rb
module Authentication
  extend ActiveSupport::Concern

  included do
    before_action :require_authentication
    helper_method :authenticated?
  end

  class_methods do
    def allow_unauthenticated_access(**options)
      skip_before_action :require_authentication, **options
    end
  end

  private
    def authenticated?
      Current.session.present?
    end

    def require_authentication
      resume_session || request_authentication
    end


    def resume_session
      Current.session = find_session_by_cookie
    end

    def find_session_by_cookie
      Session.find_by(id: cookies.signed[:session_id])
    end


    def request_authentication
      session[:return_to_after_authenticating] = request.url
      redirect_to new_session_url
    end

    def after_authentication_url
      session.delete(:return_to_after_authenticating) || root_url
    end


    def start_new_session_for(user)
      user.sessions.create!(user_agent: request.user_agent, ip_address: request.remote_ip).tap do |session|
        Current.session = session
        cookies.signed.permanent[:session_id] = { value: session.id, httponly: true, same_site: :lax }
      end
    end

    def terminate_session
      Current.session.destroy
      cookies.delete(:session_id)
    end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def show
    @commodities = Commodity.all
    @commodity_ownerships = Current.user.commodity_ownerships.with_total_value
  end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
  allow_unauthenticated_access
  before_action :set_user_by_token, only: %i[ edit update ]

  def new
  end

  def create
    if user = User.find_by(email: params[:email])
      PasswordsMailer.reset(user).deliver_later
    end

    redirect_to new_session_url, notice: "Password reset instructions sent (if user with that email address exists)."
  end

  def edit
  end

  def update
    if @user.update(params.permit(:password, :password_confirmation))
      redirect_to new_session_url, notice: "Password has been reset."
    else
      redirect_to edit_password_url(params[:token]), alert: "Passwords did not match."
    end
  end

  private
    def set_user_by_token
      @user = User.find_by_password_reset_token!(params[:token])
    rescue ActiveSupport::MessageVerifier::InvalidSignature
      redirect_to new_password_url, alert: "Password reset link is invalid or has expired."
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  allow_unauthenticated_access only: %i[ new create ]
  rate_limit to: 10, within: 3.minutes, only: :create, with: -> { redirect_to new_session_url, alert: "Try again later." }

  def new
  end

  def create
    if user = User.authenticate_by(params.permit(:email, :password))
      start_new_session_for user
      redirect_to after_authentication_url
    else
      redirect_to new_session_url, alert: "Try another email address or password."
    end
  end

  def destroy
    terminate_session
    redirect_to new_session_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/commodities/show.html.erb
<div class="bg-white rounded-xl flex flex-col w-full p-8">
  <div class="flex justify-end">
    <%= link_to "Buy", purchase_commodity_path(@commodity) %>
  </div>

  <div class="flex justify-between">
    <div>
      <%= @commodity.name %>
    </div>
    <div>
      <%= number_to_currency(@commodity.price) %>
    </div>
  </div>

  <div class="flex justify-between">
    <div>
      You own: <%= @commodity_owned %>
    </div>
    <div>
      <%= number_to_currency(@commodity_owned * @commodity.price)  %>
    </div>
  </div>
</div>

app/views/commodity_transactions/new.html.erb
<%= form_with model: [@commodity, @commodity_transaction] do |f| %>
  <%= f.hidden_field :transaction_type %>

  <%= f.number_field :quantity,
    step: 1,
    min: 1,
    required: true
  %>

  <%= f.submit %>
<% end %>

app/views/dashboard/show.html.erb
<div class="bg-white rounded-xl shadow-xl p-5 pb-0 w-full">
  <div class="flex justify-between text-xl font-semibold">
    <span>
      My Assets
    </span>
    <span>
      <%= number_to_currency @commodity_ownerships.sum(&:total_value) %>
    </span>
  </div>

  <div class="mt-5 flex flex-col gap-2 divide-y divide-slate-300 border-t border-slate-300 -mx-5 px-5 pb-2">
    <% @commodity_ownerships.each do |commodity_ownership| %>
      <%= link_to commodity_path(commodity_ownership.commodity), class: "flex justify-between py-2 -mx-5 px-5" do %>
        <div class="my-auto">
          <%= commodity_ownership.commodity.name %>
        </div>
        <div class="flex flex-col">
          <div class="text-end text-lg">
            <%= number_to_currency commodity_ownership.total_value %>
          </div>
          <div class="text-end text-sm font-light">
            <%= number_to_currency commodity_ownership.commodity.price %> * <%= commodity_ownership.quantity %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

<div class="bg-white rounded-xl shadow-xl p-5 pb-0 w-full">
  <span class="text-xl font-semibold">
    Commodities Prices
  </span>

  <div class="mt-5 flex flex-col gap-2 divide-y divide-slate-300 border-t border-slate-300 -mx-5 px-5 pb-2">
    <% @commodities.each do |commodity| %>
      <%= link_to commodity_path(commodity), class: "flex justify-between py-2 -mx-5 px-5" do %>
        <div class="my-auto">
          <%= commodity.name %>
        </div>
        <div class="text-end">
          <%= number_to_currency commodity.price %>
        </div>
      <% end %>
    <% end %>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Stockticker" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/views/stylesheets %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-slate-100">
    <main class="container mx-auto mt-8 flex flex-col md:flex-row gap-5">
      <%= yield %>
    </main>
  </body>
</html>